name: DiAs
description: "DiAs adalah aplikasi digital yang dirancang untuk mempermudah akses ke informasi dan dokumentasi dalam bidang keperawatan."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  persistent_bottom_nav_bar: ^6.2.1
  simple_shadow: ^0.3.1
  page_transition: ^2.1.0
  lottie: ^3.1.3
  http: ^1.2.2
  equatable: ^2.0.5
  shared_preferences: ^2.3.2
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  intl: ^0.19.0
  webview_flutter: ^4.10.0
  awesome_dialog: ^3.2.1
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  flutter_launcher_icons: "^0.14.2"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 25

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/lotties/
    - assets/icons/
    - assets/icon/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
